### ISSUE TITLE
Ukrainian lenguge

### ISSUE THREAD

**Issue by MetenBouldry** [Penguin-Spy/overhead-electrification#1]
[mod-name]
overhead-electrification=Повітряна електрифікація
[mod-setting-name]
oe-train-update-rate=Частота оновлення поїздів
oe-se-space-train-compat=База даних SE Space Trains
oe-se-space-train-remove-batteries=Вийміть батареї SE Space Trains
[mod-setting-description]
oe-train-update-rate=Оновлювати потяги кожні n тиків. За замовчуванням кожні 6 тиків, тобто 10 разів на секунду.\nБільше значення покращує продуктивність, але за рахунок зниження точності енергоспоживання.\nОновлення потягів розподілено на декілька тиків, щоб запобігти стрибкам продуктивності.
oe-se-space-train-compat=Модифікує космічні поїзди для живлення від повітряних контактних ліній [font=default-bold]замість[/font] батарей.
oe-se-space-train-remove-batteries=Повністю видаляє елементи акумуляторного блоку та зарядний пристрій.\nЗа замовчуванням увімкнено; ви можете тимчасово вимкнути цю опцію під час завантаження збереження, яке містить ці елементи.\nЗверніть увагу, що навіть якщо ці елементи існують, вони не можуть бути використані космічними локомотивами.\nНе має ефекту, якщо сумісність із космічними поїздами SE вимкнена.
[entity-name]
oe-electric-locomotive=Електровоз
oe-transformer=Трансформатор контактної мережі
oe-catenary-pole=Опора контактної мережі

[entity-description]
oe-electric-locomotive=Виконує автоматизовані графіки та тягне рухомий склад. Живлення від повітряних ліній електропередач.
oe-transformer=Перетворює заводську енергію на напругу, необхідну для роботи електровозів.
oe-catenary-pole=Підтримує повітряні лінії електропередач, що використовуються для живлення електровозів.

[technology-name]
oe-electric-railway=Електрична залізниця
oe-electric-railway-signals=Електричні залізничні сигнали

[technology-description]
oe-electric-railway=Локомотиви, що живляться від повітряних ліній електропередач.
oe-electric-railway-signals=Залізничні сигнали, вбудовані в опори контактної мережі.

[shortcut-name]
oe-toggle-powered-rail-view=Вигляд рейки з перемикачем з електроприводом

# this is a core game string category
[cant-build-reason]
oe-pole-too-close=Занадто близько до існуючої опори контактної мережі
oe-invalid-pole-position=Неправильне положення полюса контактної мережі

[item-name]
# this is what would be shown when hovering over the fuel slot in the locomotive, but there are 0 fuel inventory slots
oe-internal-fuel=Працює від електрики

[command-help]
oe-debug=Команда налагодження для повітряної електрифікації

**Comment by Penguin-Spy** [comment]
Thanks! added in version 0.1.2, should be on the mod portal now :)
